worker_processes  1;

events {
    worker_connections  6144;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # === Upstream: адреса твоих микросервисов ===
    upstream root_app {
        server 127.0.0.1:8000;
    }
    upstream client_app {
        server 127.0.0.1:8002;
    }
    upstream ws_app {
        server 127.0.0.1:8001;
    }

    # === Root server (пункт 3 + 7) ===
    server {
        listen 80;
        server_name root.local;

        location / {
            proxy_pass http://root_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header Connection "";
        }
    }

    # === Client server (пункт 6) ===
    server {
        listen 80;
        server_name client.local;

        location / {
            proxy_pass http://client_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header Connection "";
        }
    }

    # === WebSocket server (пункт 5) ===
    server {
        listen 80;
        server_name ws.local;

        location / {
            proxy_pass http://ws_app;
            
            # ⚡ Критически важно для WebSocket:
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Таймауты для долгого соединения
            proxy_read_timeout 86400;
            proxy_send_timeout 86400;
	    proxy_set_header Connection "";        }
    }
}
